### ISSUE TITLE
Using MeshZone as CrossZone not working

### ISSUE THREAD

**Issue by revyTH** [drawcall/three.proton#10]
Hi, thanks for this beautiful project!

I am trying to use a MeshZone as CrossZone for the emitter, basically the goal is to have the particles destroyed as soon as they go outside of the MeshZone (defined through a threejs geometry).

My current attempt does not work, the particles are not destroyed even if when they are outside the mesh.
This is the live plunker:

[https://plnkr.co/edit/6y0xLCaFxSL176J6GQ9R](https://plnkr.co/edit/6y0xLCaFxSL176J6GQ9R)

**Comment by a-jie** [comment]
Sorry, MeshZone does not currently support destroy events. Because mesh is often more complicated, although there are ways to do it, but if it is just a box, it may be implemented with boxzone.
