### ISSUE TITLE
Uncaught (in promise) ReferenceError: THREE is not defined

### ISSUE THREAD

**Issue by maemaemae3** [drawcall/three.proton#14]
Hi thanks for the great library!
I'm using this library in Vuejs(Nuxt.js) project, and I'm getting error of the subject.
When I put 
```
const THREE = require("three");
```
on top of the `/project/node_modules/three.proton.js/build/proton.min.js` , everything works well, but... its a weird kind of solution.
does anyone has any idea to solve it?

**Comment by drawcall** [comment]
Sorry, I haven’t followed this project for a while. The problem has been fixed, please download the latest package version

A usage example is here [https://codesandbox.io/s/three-spriterender-39rqy](https://codesandbox.io/s/three-spriterender-39rqy)

**Comment by maemaemae3** [comment]
thank you very much! Its fixed!
