### ISSUE TITLE
Upstream changes from Proton

### ISSUE THREAD

**Issue by ghost** [drawcall/three.proton#17]
I noticed that three.proton has not been updated since Jul 2020, compared to Proton, which has been actively maintained. Will three.proton ever get upstream fixes/changes/updates?

**Comment by drawcall** [comment]
Oh yes, I did not update for a while. But it still works well. If you have any problems, you can tell me

**Comment by ghost** [comment]
I was curious about using it in a project, and was deciding on a library to use. Thanks for the info!
