### ISSUE TITLE
Infinite stream of particles.

### ISSUE THREAD

**Issue by trusktr** [drawcall/three.proton#4]
Hello! This is really cool! 

Suppose I want to make a stream of particles, like [this one](https://codepen.io/cvaneenige/pen/rjVvdM?js-preprocessor=none), but infinite so that it seems like it streams forever from one spot to the other spot.

Is this possible to do with three.proton?

**Comment by drawcall** [comment]
Oh I want to find someone you can use protons to achieve, such as this example

https://drawcall.github.io/Proton/examples/render/pixel/thousand.html
