### ISSUE TITLE
How to change emitter position?

### ISSUE THREAD

**Issue by noisiak** [drawcall/three.proton#5]
In the repo readme example, the emitter is position is set to a position given by pointZone and that position only have two parameters.

I played with these parameters and found that only the first one works, but the position change in a very unexpected way. I thought pointZone parameters were for X and Y coordinates, but instead when changing the first parameter, the emitter moves in the vertical axis and the horizontal axis at the same time (it goes up, to the front and to the right).

Any ideas?

**Comment by a-jie** [comment]
Emitter inherits from Particle, so it can be set as follows
```
Emitter.p.x = x;
Emitter.p.y = y;
```

**Comment by noisiak** [comment]
Hey thanks! it worked fine.
