### ISSUE TITLE
How to link Proton emitter to 3DObject

### ISSUE THREAD

**Issue by cptSwing** [drawcall/three.proton#8]
Hello, this is less of a direct support question as I am aware of - since I can't find a good place to ask Proton-with-three related questions though, here it is: 

Basically I am trying to link a particle emitter to a `THREE.3DObject` (linking a jet-stream to an airplane in this case), to have it organised as a child of the object and follow its movement etc. Using `airplane.add(particleEmitter)` fails, since the emitters are not 3DObjects. Creating a new `THREE.Group` and adding both the airplane and the emitter fails for the very same reason. Currently I am setting the particles' x/y/z to the airplanes' x/y/z each frame in the update function, this seems like an awfully hacky way of doing things, though?

Any comments appreciated!

**Comment by a-jie** [comment]
Sorry, I just saw this question. Through your description, I can't fully understand what problems you have encountered, maybe you can get some inspiration through this example.

http://a-jie.github.io/Proton/example/game/crafty/asteroids.html

**Comment by cptSwing** [comment]
Hey @a-jie thank you for the reply, and for the link. It basically confirms what I've been doing myself, ie 
```
fighterEmitter.p.x = player._x + player.w / 2 + R * Math.sin(-angle) - 5;
fighterEmitter.p.y = player._y + player.h / 2 + R * Math.cos(-angle);
fighterEmitter.rotation = -player.rotation;
```

which is similar to what I am doing in my `three` update() function. I would love for proton emitters to be objects (`Object3D`?) which can be parented to `three` objects via `object.add( protonEmitterWhatever )` ... it'd make scene management easier for sure!

Either way, I've been enjoying my very limited time with Proton!
