### ISSUE TITLE
Why does adding event listener not work?

### ISSUE THREAD

**Issue by zhaozj89** [drawcall/three.proton#9]
For example,

`particle_engine_proton.addEventListener(Proton.PARTICLE_CREATED, function(particle) {
    let num = particle_engine_proton.getCount();
}`

It works in proton, but not three.proton.

Thanks.

**Comment by drawcall** [comment]
I'm very sorry, I haven't followed this library for a while, yes there are some subtle differences between three.proton and Proton.
